run:
	python photo_picker.py "input_photos/sample"

tidy:
	python -m black photo_picker.py

install:
	python -m pip install -r requirements.txt

freeze:
	python -m pip freeze

clean:
	rm -f output_photos/*
